---
- name: Install docker
  yum:
    name:
      - docker-1.13.1
    state: present
  when: (openshift_version | string) in ["3.9", "3.10", "3.11"]
  become: true

- name: Install OpenShift playbooks (3.9)
  yum:
    name:
      - atomic-openshift-utils
    state: present
  when:
    - openshift_version_minor is not defined
    - (openshift_version | string) in ["3.9"]
  become: true

- name: Install OpenShift playbooks (3.9) - minor version
  yum:
    name:
      - atomic-openshift-utils-{{ openshift_version_minor }}
    state: present
  when:
    - openshift_version_minor is defined
    - (openshift_version | string) in ["3.9"]
  become: true

- name: Install OpenShift playbooks (3.10, 3.11)
  yum:
    name:
      - openshift-ansible
    state: present
  when:
    - openshift_version_minor is not defined
    - (openshift_version | string) in ["3.10", "3.11"]
  become: true

- name: Install OpenShift playbooks (3.10, 3.11) - minor version
  yum:
    name:
      - openshift-ansible-{{ openshift_version_minor }}
    state: present
  when:
    - openshift_version_minor is defined
    - (openshift_version | string) in ["3.10", "3.11"]
  become: true

- name: Start and enable docker
  service:
    name: docker
    enabled: true
    state: started
  become: true

- name: Copy EC2 key
  copy:
    src: "{{ ec2_key_file }}"
    dest: ~/.ssh/id_rsa
    mode: 0600
    backup: true
