---
- name: Disable amazon-id YUM plugin
  lineinfile:
    dest: /etc/yum/pluginconf.d/amazon-id.conf
    regexp: "^enabled="
    line: "enabled=0"
  register: disable_plugin_amazon_id
  become: true

- name: Disable rhui-lb YUM plugin
  lineinfile:
    dest: /etc/yum/pluginconf.d/rhui-lb.conf
    regexp: "^enabled="
    line: "enabled=0"
  register: disable_plugin_rhui_lb
  become: true

- name: Stop choose_repo service
  service:
    name: choose_repo
    state: stopped
  become: true

- name: Disable choose_repo service
  service:
    name: choose_repo
    enabled: false
  become: true

- name: Disable all repos
  command: "yum-config-manager --disable '*'"
  when: >
    disable_plugin_amazon_id.changed
    or disable_plugin_rhui_lb.changed
  register: disable_all_repos
  become: true
