---

- import_tasks: certs.yml
  when: letsencrypt_cert_generation

- name: Copy Ansible config
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true

- name: Copy hosts template
  template:
    src: hosts.{{ cluster_type }}.{{ openshift_version }}.ini.j2
    dest: /etc/ansible/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true

- name: Run OpenShift prerequisites
  command: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
  async: 900  # 15 minutes
  poll: 30
  tags: openshift_deploy_cluster

- name: Run OpenShift installer (this will take a while!)
  command: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
  async: 5400  # 90 minutes
  poll: 30
  tags: openshift_deploy_cluster
