---
- hosts: localhost
  tasks:
    - name: Start EC2 instances
      ec2_instance:
        region: "{{ aws_region }}"
        filters:
          tag:OpenShiftClusterNameVerbose: "{{ hostvars.localhost.cluster_name_verbose }}"
        state: started
