---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Stop EC2 instances
      ec2_instance:
        region: "{{ aws_region }}"
        filters:
          tag:OpenShiftClusterNameVerbose: "{{ hostvars.localhost.cluster_name_verbose }}"
        state: stopped
